import type { Metadata, Viewport } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: React.PropsWithChildren<{}>) {
  return (
    <html className={`${GeistSans.className}`} lang="en">
      <div>{children}</div>
    </html>
  );
}
